export const TOP_300_CITIES: Array<{ city: string; state: string }> = [
  { city: 'New York', state: 'NY' }, { city: 'Los Angeles', state: 'CA' },
  { city: 'Chicago', state: 'IL' }, { city: 'Houston', state: 'TX' },
  { city: 'Phoenix', state: 'AZ' }, { city: 'Philadelphia', state: 'PA' },
  { city: 'San Antonio', state: 'TX' }, { city: 'San Diego', state: 'CA' },
  { city: 'Dallas', state: 'TX' }, { city: 'San Jose', state: 'CA' },
  { city: 'Austin', state: 'TX' }, { city: 'Jacksonville', state: 'FL' },
  { city: 'Fort Worth', state: 'TX' }, { city: 'Columbus', state: 'OH' },
  { city: 'Charlotte', state: 'NC' }, { city: 'Indianapolis', state: 'IN' },
  { city: 'San Francisco', state: 'CA' }, { city: 'Seattle', state: 'WA' },
  { city: 'Denver', state: 'CO' }, { city: 'Nashville', state: 'TN' },
  { city: 'Oklahoma City', state: 'OK' }, { city: 'El Paso', state: 'TX' },
  { city: 'Washington', state: 'DC' }, { city: 'Las Vegas', state: 'NV' },
  { city: 'Louisville', state: 'KY' }, { city: 'Memphis', state: 'TN' },
  { city: 'Portland', state: 'OR' }, { city: 'Baltimore', state: 'MD' },
  { city: 'Milwaukee', state: 'WI' }, { city: 'Albuquerque', state: 'NM' },
  { city: 'Tucson', state: 'AZ' }, { city: 'Fresno', state: 'CA' },
  { city: 'Sacramento', state: 'CA' }, { city: 'Mesa', state: 'AZ' },
  { city: 'Kansas City', state: 'MO' }, { city: 'Atlanta', state: 'GA' },
  { city: 'Omaha', state: 'NE' }, { city: 'Colorado Springs', state: 'CO' },
  { city: 'Raleigh', state: 'NC' }, { city: 'Long Beach', state: 'CA' },
  { city: 'Virginia Beach', state: 'VA' }, { city: 'Minneapolis', state: 'MN' },
  { city: 'Tampa', state: 'FL' }, { city: 'New Orleans', state: 'LA' },
  { city: 'Arlington', state: 'TX' }, { city: 'Wichita', state: 'KS' },
  { city: 'Bakersfield', state: 'CA' }, { city: 'Aurora', state: 'CO' },
  { city: 'Anaheim', state: 'CA' }, { city: 'Santa Ana', state: 'CA' },
  { city: 'Corpus Christi', state: 'TX' }, { city: 'Riverside', state: 'CA' },
  { city: 'Lexington', state: 'KY' }, { city: 'St. Louis', state: 'MO' },
  { city: 'Pittsburgh', state: 'PA' }, { city: 'Anchorage', state: 'AK' },
  { city: 'Stockton', state: 'CA' }, { city: 'Cincinnati', state: 'OH' },
  { city: 'St. Paul', state: 'MN' }, { city: 'Toledo', state: 'OH' },
  { city: 'Greensboro', state: 'NC' }, { city: 'Newark', state: 'NJ' },
  { city: 'Plano', state: 'TX' }, { city: 'Henderson', state: 'NV' },
  { city: 'Lincoln', state: 'NE' }, { city: 'Buffalo', state: 'NY' },
  { city: 'Fort Wayne', state: 'IN' }, { city: 'Jersey City', state: 'NJ' },
  { city: 'Chula Vista', state: 'CA' }, { city: 'Orlando', state: 'FL' },
  { city: 'St. Petersburg', state: 'FL' }, { city: 'Laredo', state: 'TX' },
  { city: 'Norfolk', state: 'VA' }, { city: 'Madison', state: 'WI' },
  { city: 'Durham', state: 'NC' }, { city: 'Lubbock', state: 'TX' },
  { city: 'Winston-Salem', state: 'NC' }, { city: 'Garland', state: 'TX' },
  { city: 'Glendale', state: 'AZ' }, { city: 'Hialeah', state: 'FL' },
  { city: 'Reno', state: 'NV' }, { city: 'Baton Rouge', state: 'LA' },
  { city: 'Irvine', state: 'CA' }, { city: 'Chesapeake', state: 'VA' },
  { city: 'Irving', state: 'TX' }, { city: 'Scottsdale', state: 'AZ' },
  { city: 'North Las Vegas', state: 'NV' }, { city: 'Fremont', state: 'CA' },
  { city: 'Gilbert', state: 'AZ' }, { city: 'San Bernardino', state: 'CA' },
  { city: 'Birmingham', state: 'AL' }, { city: 'Rochester', state: 'NY' },
  { city: 'Richmond', state: 'VA' }, { city: 'Spokane', state: 'WA' },
  { city: 'Des Moines', state: 'IA' }, { city: 'Montgomery', state: 'AL' },
  { city: 'Modesto', state: 'CA' }, { city: 'Fayetteville', state: 'NC' },
  { city: 'Tacoma', state: 'WA' }, { city: 'Shreveport', state: 'LA' },
  { city: 'Akron', state: 'OH' }, { city: 'Aurora', state: 'IL' },
  { city: 'Yonkers', state: 'NY' }, { city: 'Huntington Beach', state: 'CA' },
  { city: 'Little Rock', state: 'AR' }, { city: 'Columbus', state: 'GA' },
  { city: 'Glendale', state: 'CA' }, { city: 'Grand Rapids', state: 'MI' },
  { city: 'Salt Lake City', state: 'UT' }, { city: 'Tallahassee', state: 'FL' },
  { city: 'Huntsville', state: 'AL' }, { city: 'Worcester', state: 'MA' },
  { city: 'Knoxville', state: 'TN' }, { city: 'Newport News', state: 'VA' },
  { city: 'Brownsville', state: 'TX' }, { city: 'Santa Clarita', state: 'CA' },
  { city: 'Providence', state: 'RI' }, { city: 'Garden Grove', state: 'CA' },
  { city: 'Oceanside', state: 'CA' }, { city: 'Chattanooga', state: 'TN' },
  { city: 'Fort Lauderdale', state: 'FL' }, { city: 'Rancho Cucamonga', state: 'CA' },
  { city: 'Santa Rosa', state: 'CA' }, { city: 'Tempe', state: 'AZ' },
  { city: 'Cape Coral', state: 'FL' }, { city: 'Oxnard', state: 'CA' },
  { city: 'Eugene', state: 'OR' }, { city: 'Peoria', state: 'IL' },
  { city: 'Elk Grove', state: 'CA' }, { city: 'Salem', state: 'OR' },
  { city: 'Ontario', state: 'CA' }, { city: 'Corona', state: 'CA' },
  { city: 'Springfield', state: 'MO' }, { city: 'Fort Collins', state: 'CO' },
  { city: 'Jackson', state: 'MS' }, { city: 'Alexandria', state: 'VA' },
  { city: 'Hayward', state: 'CA' }, { city: 'Clarksville', state: 'TN' },
  { city: 'Lancaster', state: 'CA' }, { city: 'Salinas', state: 'CA' },
  { city: 'Palmdale', state: 'CA' }, { city: 'Sunnyvale', state: 'CA' },
  { city: 'Pomona', state: 'CA' }, { city: 'Escondido', state: 'CA' },
  { city: 'Kansas City', state: 'KS' }, { city: 'Torrance', state: 'CA' },
  { city: 'Pasadena', state: 'TX' }, { city: 'Paterson', state: 'NJ' },
  { city: 'Rockford', state: 'IL' }, { city: 'Savannah', state: 'GA' },
  { city: 'Bridgeport', state: 'CT' }, { city: 'Mesquite', state: 'TX' },
  { city: 'Syracuse', state: 'NY' }, { city: 'Roseville', state: 'CA' },
  { city: 'Surprise', state: 'AZ' }, { city: 'Torrance', state: 'CA' },
  { city: 'Denton', state: 'TX' }, { city: 'Victorville', state: 'CA' },
  { city: 'Killeen', state: 'TX' }, { city: 'Macon', state: 'GA' },
  { city: 'Pasadena', state: 'CA' }, { city: 'Olathe', state: 'KS' },
  { city: 'Hampton', state: 'VA' }, { city: 'Warren', state: 'MI' },
  { city: 'West Valley City', state: 'UT' }, { city: 'Columbia', state: 'SC' },
  { city: 'Sterling Heights', state: 'MI' }, { city: 'New Haven', state: 'CT' },
  { city: 'Miramar', state: 'FL' }, { city: 'Thousand Oaks', state: 'CA' },
  { city: 'Sioux Falls', state: 'SD' }, { city: 'Cedar Rapids', state: 'IA' },
  { city: 'Topeka', state: 'KS' }, { city: 'Charleston', state: 'SC' },
  { city: 'Visalia', state: 'CA' }, { city: 'Waco', state: 'TX' },
  { city: 'Elizabeth', state: 'NJ' }, { city: 'Fullerton', state: 'CA' },
  { city: 'Gainesville', state: 'FL' }, { city: 'Coral Springs', state: 'FL' },
  { city: 'Stamford', state: 'CT' }, { city: 'Concord', state: 'CA' },
  { city: 'Hartford', state: 'CT' }, { city: 'Roseville', state: 'CA' },
  { city: 'Thornton', state: 'CO' }, { city: 'Kent', state: 'WA' },
  { city: 'Abilene', state: 'TX' }, { city: 'Beaumont', state: 'TX' },
  { city: 'Murfreesboro', state: 'TN' }, { city: 'Independence', state: 'MO' },
  { city: 'Peoria', state: 'AZ' }, { city: 'Arvada', state: 'CO' },
  { city: 'El Monte', state: 'CA' }, { city: 'Downey', state: 'CA' },
  { city: 'Clearwater', state: 'FL' }, { city: 'Costa Mesa', state: 'CA' },
  { city: 'Inglewood', state: 'CA' }, { city: 'North Las Vegas', state: 'NV' },
  { city: 'Antioch', state: 'CA' }, { city: 'Manchester', state: 'NH' },
  { city: 'Provo', state: 'UT' }, { city: 'West Jordan', state: 'UT' },
  { city: 'Murrieta', state: 'CA' }, { city: 'Lowell', state: 'MA' },
  { city: 'Lansing', state: 'MI' }, { city: 'Glendale', state: 'CA' },
  { city: 'Elgin', state: 'IL' }, { city: 'Temecula', state: 'CA' },
  { city: 'Waterbury', state: 'CT' }, { city: 'Springfield', state: 'MA' },
  { city: 'Peoria', state: 'IL' }, { city: 'Columbia', state: 'MO' },
  { city: 'Fargo', state: 'ND' }, { city: 'Boise', state: 'ID' },
  { city: 'McKinney', state: 'TX' }, { city: 'Frisco', state: 'TX' },
  { city: 'Overland Park', state: 'KS' }, { city: 'Grand Prairie', state: 'TX' },
  { city: 'Tallahassee', state: 'FL' }, { city: 'Flint', state: 'MI' },
  { city: 'Reno', state: 'NV' }, { city: 'Ann Arbor', state: 'MI' },
  { city: 'Oxnard', state: 'CA' }, { city: 'Chattanooga', state: 'TN' },
  { city: 'Rochester', state: 'MN' }, { city: 'Billings', state: 'MT' },
  { city: 'Spokane Valley', state: 'WA' }, { city: 'Laredo', state: 'TX' },
  { city: 'Rialto', state: 'CA' }, { city: 'Cary', state: 'NC' },
  { city: 'Dayton', state: 'OH' }, { city: 'Hampton', state: 'VA' },
  { city: 'Shreveport', state: 'LA' }, { city: 'Augusta', state: 'GA' },
  { city: 'Moreno Valley', state: 'CA' }, { city: 'Fontana', state: 'CA' },
  { city: 'Modesto', state: 'CA' }, { city: 'Glendale', state: 'AZ' },
  { city: 'Akron', state: 'OH' }, { city: 'Yonkers', state: 'NY' },
  { city: 'Fayetteville', state: 'AR' }, { city: 'Amarillo', state: 'TX' },
  { city: 'Shreveport', state: 'LA' }, { city: 'Mobile', state: 'AL' },
  { city: 'Little Rock', state: 'AR' }, { city: 'Columbus', state: 'GA' },
  { city: 'Oxnard', state: 'CA' }, { city: 'Pomona', state: 'CA' },
  { city: 'Fort Wayne', state: 'IN' }, { city: 'Knoxville', state: 'TN' },
  { city: 'Chattanooga', state: 'TN' }, { city: 'Worcester', state: 'MA' },
  { city: 'Providence', state: 'RI' }, { city: 'Brownsville', state: 'TX' },
];
